name: auth_management_biometric_delegate
description: "Streamlines authentication processes through biometric methods, prioritizing security and user convenience."
version: 1.0.3
repository: https://github.com/P-YMR/flutter_auth_management.git

environment:
  sdk: '>=3.3.3 <4.0.0'
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  local_auth: ^2.2.0
  local_auth_android: ^1.0.41
  local_auth_darwin: ^1.3.1
  local_auth_platform_interface: ^1.0.10
  local_auth_windows: ^1.0.10
  auth_management_delegates: ^1.0.2
#  auth_management_delegates:
#    path: ../auth_management_delegate

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter: