name: auth_management_firebase
description: "Streamlines authentication processes by integrating Oauth's authentication services, ensuring secure access to digital platforms."
version: 1.0.0
repository: https://github.com/P-YMR/flutter_auth_management.git

environment:
  sdk: '>=3.4.3 <4.0.0'
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

  auth_management:
    path: ../
  firebase_auth: ^5.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
