name: auth_management_apple_delegate
description: "Facilitates seamless authentication via Apple's authentication services, ensuring secure access to digital platforms."
version: 1.0.3
repository: https://github.com/P-YMR/flutter_auth_management.git

environment:
  sdk: '>=3.3.3 <4.0.0'
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  sign_in_with_apple: ^6.1.1
  auth_management_delegates: ^1.0.2
#  auth_management_delegates:
#    path: ../auth_management_delegate

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter: