name: auth_management_facebook_delegate
description: "Enables hassle-free login experiences leveraging Facebook's authentication services, ensuring seamless access to digital platforms."
version: 1.0.3
repository: https://github.com/P-YMR/flutter_auth_management.git

environment:
  sdk: '>=3.3.3 <4.0.0'
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_facebook_auth: ^7.0.1
  auth_management_delegates: ^1.0.2
#  auth_management_delegates:
#    path: ../auth_management_delegate

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter: