name: auth_management_delegates
description: "Auth management delegate simplifies login with support for OAuth and biometric methods, ensuring secure access and seamless user experience."
version: 1.0.0
repository: https://github.com/P-YMR/flutter_auth_management.git

environment:
  sdk: '>=3.3.3 <4.0.0'
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.2

flutter: